# Generated by Django 6.1 on 2026-09-12 07:43

import django.db.models.deletion
import portfolios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.UUIDField(default=portfolios.models.nfc_card_token_generator, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('UNLINKED', 'Unlinked')], default='ACTIVE', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('last_tapped_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='portfolios.profile')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
