# Generated by Django 6.1 on 2026-09-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_profile_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Provide key-value pairs in JSON format, e.g., {"github": "https://...", "linkedin": "https://...", "twitter": "https://..."}'),
        ),
    ]
