# Generated by Django 6.0.7 on 2026-09-14 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_nfccard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('headline', models.CharField(default='SasaPay Authorized Agent', max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('referral_code', models.CharField(max_length=100, unique=True)),
                ('services_offered', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AgentNFCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('UNLINKED', 'Unlinked')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_tapped_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='portfolios.agentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
