# Generated by Django 6.1 on 2026-09-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_agentprofile_agentnfccard'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccard',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='portfolios.agentprofile'),
        ),
        migrations.AlterField(
            model_name='agentnfccard',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_nfc_cards', to='portfolios.agentprofile'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
