# Generated by Django 6.1 on 2026-09-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_nfccard_agent_profile_alter_agentnfccard_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='card_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
