# Generated by Django 6.1 on 2026-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_remove_profile_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': 'Agent Profile', 'verbose_name_plural': 'Agent Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
