# Generated by Django 6.1 on 2026-09-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_profile_slug_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
    ]
