# Generated by Django 6.1 on 2026-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_remove_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Direct image URL for agent avatar', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Direct image URL for profile avatar', max_length=500, null=True),
        ),
    ]
