# Generated by Django 6.1 on 2026-09-16 09:41

from django.db import migrations, models


def populate_headlines(apps, schema_editor):
    AgentProfile = apps.get_model('portfolios', 'AgentProfile')
    AgentProfile.objects.filter(headline__isnull=True).update(
        headline='SasaPay Authorized Agent',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_agentprofile_avatar_url_profile_avatar_url'),
    ]

    operations = [
        migrations.RunPython(populate_headlines, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agentprofile',
            name='headline',
            field=models.CharField(blank=True, default='SasaPay Authorized Agent', max_length=255),
        ),
    ]
