# Generated by Django 6.1 on 2026-09-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_alter_agentprofile_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_cards', to='portfolios.agentprofile'),
        ),
    ]
