# Generated by Django 6.1 on 2026-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_alter_nfccard_agent_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfccard',
            options={'verbose_name': 'NFC Card', 'verbose_name_plural': 'NFC Cards'},
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
