# Generated by Django 6.1 on 2026-09-16 11:19

import portfolios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_alter_nfccard_options_agentprofile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='services_offered',
            field=models.JSONField(blank=True, default=portfolios.models.default_sasapay_services, help_text='Provide a JSON array of services, e.g., ["Cash In & Cash Out", "P2P Transfers"]'),
        ),
    ]
