# Generated by Django 6.1 on 2026-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_alter_agentprofile_services_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='sasapay_checkout_url',
            field=models.URLField(blank=True, help_text='SasaPay checkout app link assigned to this agent.', max_length=500, null=True),
        ),
    ]
