# Generated by Django 6.1 on 2026-09-19 10:01

from django.db import migrations


def update_sasapay_urls(apps, schema_editor):
    AgentProfile = apps.get_model('portfolios', 'AgentProfile')

    for agent in AgentProfile.objects.all():
        if not agent.sasapay_checkout_url or not str(agent.sasapay_checkout_url).strip():
            identifier = agent.agent_id or agent.slug or 'default'
            agent.sasapay_checkout_url = f'https://checkout.sasapay.app/pay/{identifier}'
            agent.save(update_fields=['sasapay_checkout_url'])


def reverse_func(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0015_agentprofile_sasapay_checkout_url'),
    ]

    operations = [
        migrations.RunPython(update_sasapay_urls, reverse_code=reverse_func),
    ]
