# Generated by Django 6.1 on 2026-09-19 10:07

from django.db import migrations


def populate_sasapay_urls(apps, schema_editor):
    AgentProfile = apps.get_model('portfolios', 'AgentProfile')

    checkout_url_map = {
        'Allano-kimani': 'https://checkout.sasapay.app/2102e1f2-a3c5-41e7-90ce-c0552c72df00',
    }

    for slug, url in checkout_url_map.items():
        AgentProfile.objects.filter(slug=slug).update(sasapay_checkout_url=url)


def reverse_func(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0016_populate_sasapay_urls'),
    ]

    operations = [
        migrations.RunPython(populate_sasapay_urls, reverse_code=reverse_func),
    ]
